#!/bin/bash

echo "🔍 Railway 环境变量检查和设置指南"
echo "======================================"

echo ""
echo "🚨 当前问题分析："
echo "✅ Email service initialized - 邮件服务正常"  
echo "❌ Redis disconnected - 这是核心问题！"
echo "原因: 验证码存储依赖Redis，Redis断开导致整个验证流程失败"
echo ""

echo "📊 必需的服务和环境变量："
echo ""
echo "🔴 1. Redis服务 (最关键!)"
echo "   在Railway控制台添加Redis数据库服务"
echo "   自动生成: REDIS_URL=redis://default:password@host:port"
echo ""

echo "📧 必需的邮箱环境变量（基于Zoho Mail官方配置）："
echo "方案一 - SSL配置（推荐）："
echo "SMTP_HOST=smtppro.zoho.com"
echo "SMTP_PORT=465"
echo "SMTP_SECURE=true"
echo "SMTP_USER=joe.deng@coldaw.app"
echo "SMTP_PASS=YKRuZF1TCbkR  # 如果启用了2FA，使用应用专用密码"
echo "FROM_EMAIL=joe.deng@coldaw.app"
echo ""
echo "方案二 - TLS配置（备选）："
echo "SMTP_HOST=smtppro.zoho.com"
echo "SMTP_PORT=587"
echo "SMTP_SECURE=false"
echo "SMTP_USER=joe.deng@coldaw.app"
echo "SMTP_PASS=YKRuZF1TCbkR  # 如果启用了2FA，使用应用专用密码"
echo "FROM_EMAIL=joe.deng@coldaw.app"
echo ""

echo "🔧 其他必需环境变量："
echo "NODE_ENV=production"
echo "JWT_SECRET=coldaw-production-secret-key-please-change-this-to-a-random-string"
echo ""

echo "📋 Railway 环境变量设置步骤："
echo "1. 访问 Railway 控制台: https://railway.app"
echo "2. 登录并选择您的 ColDAW 项目"
echo "3. 在项目页面中，点击您的服务(app)"
echo "4. 进入 'Variables' 标签页"
echo "5. 点击 'New Variable' 按钮"
echo "6. 逐一添加上述环境变量"
echo "7. 确保变量名称完全匹配（区分大小写）"
echo "8. 保存后 Railway 会自动触发重新部署"
echo ""

echo "🔬 验证步骤："
echo "1. 等待重新部署完成（通常需要3-5分钟）"
echo "2. 访问您的应用日志页面"
echo "3. 查找以下日志输出："
echo "   '🔍 Email service initialization - Environment variables check:'"
echo "4. 确认所有变量都显示为 'SET'"
echo "5. 查找 'Email service initialized successfully' 消息"
echo "6. 访问 https://www.coldaw.app/api/health 检查服务状态"
echo ""

echo "🚨 重要注意事项："
echo "- SMTP_SECURE=true (因为 smtppro.zoho.com 使用 465 端口)"
echo "- 不要在变量值前后添加引号"
echo "- 确保没有多余的空格"
echo "- Railway 环境变量严格区分大小写"
echo "- 如果之前设置过这些变量，请检查是否值正确"
echo ""

echo "🔄 Zoho Mail 特定排查步骤："
echo "1. 检查是否启用了两步验证（2FA）："
echo "   - 登录 Zoho Mail → Settings → Security"
echo "   - 如果启用了2FA，需要生成应用专用密码"
echo "   - App Passwords → New App Password → 替换SMTP_PASS"
echo ""
echo "2. 验证域名状态："
echo "   - 确保 coldaw.app 域名已在Zoho中验证"
echo "   - 检查邮箱 joe.deng@coldaw.app 可以正常登录"
echo ""
echo "3. 尝试不同端口配置："
echo "   - 如果465端口有问题，尝试587端口(TLS)"
echo "   - 更改SMTP_PORT=587 和 SMTP_SECURE=false"
echo ""
echo "4. 检查Zoho账户限制："
echo "   - 确认付费账户状态正常"
echo "   - 检查每日发送限制是否达到"
echo ""

echo "📞 调试命令："
echo "在 Railway 控制台的 'Deployments' 页面查看实时日志"
echo "或使用 Railway CLI: railway logs --follow"