#!/bin/bash

# Zoho Mail 配置快速检查清单
echo "📧 Zoho Mail 配置检查清单"
echo "=========================="

echo ""
echo "✅ 账户设置:"
echo "□ 1. 已注册 Zoho Mail 账户"
echo "□ 2. 已验证邮箱地址"
echo "□ 3. 已启用两步验证"
echo "□ 4. 已生成应用专用密码"

echo ""
echo "🔧 SMTP 凭据配置:"
echo "□ 1. SMTP_HOST=smtp.zoho.com"
echo "□ 2. SMTP_PORT=587"
echo "□ 3. SMTP_SECURE=false"
echo "□ 4. SMTP_USER=your-email@your-domain.com"
echo "□ 5. SMTP_PASS=应用专用密码（不是登录密码）"

echo ""
echo "🌐 域名设置:"
echo "□ 1. 已在 Zoho 中添加自定义域名"
echo "□ 2. DNS 记录配置正确："
echo "   □ MX 记录指向 Zoho 服务器"
echo "   □ TXT 记录用于验证和 SPF"
echo "   □ CNAME 记录（如需要）"
echo "□ 3. 域名验证状态为已验证"

echo ""
echo "📋 Railway 环境变量:"
echo "在 Railway 项目中设置以下环境变量："
echo "SMTP_HOST=smtp.zoho.com"
echo "SMTP_PORT=587"
echo "SMTP_SECURE=false"
echo "SMTP_USER=your-email@your-domain.com"
echo "SMTP_PASS=your-app-password"

echo ""
echo "🧪 测试步骤:"
echo "1. 部署到 Railway"
echo "2. 访问 /api/health 检查邮件服务状态"
echo "3. 尝试发送验证邮件"
echo "4. 检查 Zoho Mail 的发送活动日志"

echo ""
echo "📞 获取帮助:"
echo "- Zoho Mail 帮助: https://help.zoho.com/portal/en/home"
echo "- SMTP 设置: https://help.zoho.com/portal/en/kb/articles/smtp-settings"
echo "- DNS 配置: https://help.zoho.com/portal/en/kb/articles/dns-settings"
echo "- Railway 支持: https://railway.app/help"

echo ""
echo "💡 常见问题:"
echo "- 必须使用应用专用密码，不能使用普通登录密码"
echo "- 确保域名已在 Zoho 中验证"
echo "- 检查 DNS 记录是否正确配置"
echo "- 确认没有超过 Zoho 的发送限制"
echo "- 新账户可能有发送限制，需要逐步提升"